# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: self-hosted
    steps:
    - name: prueba
      run: |
          pwd
    - uses: actions/checkout@v2
    - name: Cache node-modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os}}-node-${{ hashfiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os}}-node-
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run build --output-path=/var/lib/tomcat/webapps/ --base-href /var/lib/tomcat/webapps/recipes-app/  --deploy-url /var/lib/tomcat/webapps/recipes-app/
